Label.find_or_create_by(title: '引っ越して来ました！')
Label.find_or_create_by(title: '引っ越します！')
Label.find_or_create_by(title: '不用品処理')
Label.find_or_create_by(title: 'イベント')
Label.find_or_create_by(title: 'さがしもの')
Label.find_or_create_by(title: '落とし物')
Label.find_or_create_by(title: '長期不在')
Label.find_or_create_by(title: '告知')
Label.find_or_create_by(title: 'パーティー')
Label.find_or_create_by(title: '緊急')
Label.find_or_create_by(title: '住居者より')
Label.find_or_create_by(title: '管理者より')
Routine.find_or_create_by(title: 'ゴミ出し', content: '毎日 / 一週間', due_date: '2019/9/1')
Routine.find_or_create_by(title: 'トイレ掃除', content: '週イチ / 一週間', due_date: '2019/9/1')