Label.find_or_create_by(title: '引っ越して来ました！')
Label.find_or_create_by(title: '引っ越します！')
Label.find_or_create_by(title: '不用品処理')
Label.find_or_create_by(title: 'イベント')
Label.find_or_create_by(title: '探しもの')
Label.find_or_create_by(title: '落とし物')
Label.find_or_create_by(title: '長期不在の連絡')
Label.find_or_create_by(title: '告知')
Label.find_or_create_by(title: 'パーティー')
Label.find_or_create_by(title: '緊急')
Label.find_or_create_by(title: '住居者より')
Label.find_or_create_by(title: '管理者より')
Label.find_or_create_by(title: 'お願いします')
Label.find_or_create_by(title: '情報')
Label.find_or_create_by(title: '共用品について')
Label.find_or_create_by(title: 'ゴミ出し・清掃について')
Routine.find_or_create_by(title: 'ゴミ出し',content: '台所のゴミ箱の管理', condition: 0)
Routine.find_or_create_by(title: 'トイレ掃除',content: 'トイレの床・便器掃除', condition: 1)
Routine.find_or_create_by(title: '台所清掃',content: '台所の床掃除', condition: 3)