Label.find_or_create_by(title: '引っ越して来ました！')
Label.find_or_create_by(title: '引っ越します！')
Label.find_or_create_by(title: '不用品処理')
Label.find_or_create_by(title: 'イベント')
Label.find_or_create_by(title: 'パーティー')
Label.find_or_create_by(title: '探しもの')
Label.find_or_create_by(title: '落とし物')
Label.find_or_create_by(title: '壊れてます')
Label.find_or_create_by(title: '長期不在の連絡')
Label.find_or_create_by(title: '緊急事案')
Label.find_or_create_by(title: '住居者より')
Label.find_or_create_by(title: '管理者より')
Label.find_or_create_by(title: 'お願いします')
Label.find_or_create_by(title: '情報')
Label.find_or_create_by(title: '共用品について')
Label.find_or_create_by(title: 'ゴミ出し・清掃について')
Label.find_or_create_by(title: 'その他の告知')
Routine.find_or_create_by(title: 'ゴミ出し',content: '台所のゴミ箱の管理', condition: 0)
Routine.find_or_create_by(title: 'トイレ掃除',content: 'トイレの床・便器掃除', condition: 1)
Routine.find_or_create_by(title: '台所清掃',content: '台所の床掃除', condition: 3)
User.create(name: 'Test_User', email: 'test1@123.com', password: '123456')
User.create(name: 'Admin_User', email: 'admin1@123.com', password: '123456', admin: true)
Personnel.find_or_create_by(last_name:'いか',first_name:'五右衛門',birth_date:'1962/11/16',room: 3,gender: 0,in_date:'2019/10/21',out_plan_date:'2020/11/20',user_id:1)